import {Schema} from "mongoose";

const placeSchema = Schema({
    placeLookup: String,
    openBibleLat: String,
    openBibleLong: String,
    kjvName: String,
    esvName: String,
    comment: String,
    featureType: String,
    placeID: Number,
    recogitoUri: String,
    recogitoLat: String,
    recogitoLon: String,
    verses: [String],
    recogitoStatus: String,
    recogitoLabel: String,
    recogitoUID: String,
    status: String,
    displayTitle: String,
    eastons: [String],
    featureSubType: String,
    verseCount: Number,
    latitude: String,
    longitude: String,
    alphaGroup: String,
    slug: String,
    dictText: [String],
    modified: String,
    rootID: [String],
    peopleDied: [String],
    precision: String,
    recogitoType: String,
    hasBeenHere: String,
    eventsHere: [String],
    dictionaryLink: String,
    dictionaryText: String,
    recogitoComments: String,
    ambiguous: Boolean,
    aliases: String,
    booksWritten: [String],
    duplicate_of: [String],
    peopleBorn: [String],
    uid: String,
    type: String
});

export default placeSchema;